version: '2.2'
services:
    pg:
        image: 'postgres:alpine'
        container_name: postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=rollout
            - POSTGRES_USER=rollout-user
            - POSTGRES_PASSWORD=rollout-password
        networks:
            - postgres
        restart: unless-stopped
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        ports:
            - '5050:80'
        environment:
            - PGADMIN_DEFAULT_EMAIL=example@example.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        networks:
            - postgres
        restart: unless-stopped
networks:
    postgres:
        driver: bridge
