version: '2.2'
services:
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:7.5.0'
        container_name: elasticsearch
        environment:
            - node.name=elasticsearch
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - 'data:/usr/share/elasticsearch/data'
        ports:
            - '9200:9200'
        networks:
            - elastic
    kibana:
        image: 'docker.elastic.co/kibana/kibana:7.5.0'
        container_name: kibana
        ports:
            - '5601:5601'
        networks:
            - elastic
        depends_on:
            - elasticsearch
volumes:
    data:
        driver: local
networks:
    elastic:
        driver: bridge
